[package]
name = "octopus-relay"
version = "0.1.0"
authors = ["Cdot Team"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.0.1"
near-contract-standards = "3.0.1"
hex = "0.4.2"