[package]
name = "octopus-relay-contract"
version = "0.1.0"
authors = ["Cdot Team"]
edition = "2018"


[dev-dependencies]
near-sdk = "=3.0.1"
near-contract-standards = "3.0.1"
near-sdk-sim = "=3.0.1"

# remember to include a line for each contract
oct-token = { path = "./oct-token" }
octopus-relay = { path = "./octopus-relay" }


[workspace]
members = ["oct-token", "octopus-relay"]